"""Read-only FastAPI serving artifacts generated by the existing Spark pipeline."""
import csv
import json
import os
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / 'outputs' / 'dashboard' / 'dashboard_data.json'
MODELS = ROOT / 'outputs' / 'results' / 'model_comparison.csv'
CHARTS = ROOT / 'outputs' / 'charts'

app = FastAPI(title='Beyond the Beat — Dashboard API', version='1.0')
app.add_middleware(
    CORSMiddleware,
    allow_origins=['http://localhost:5173', 'http://127.0.0.1:5173'],
    allow_credentials=False,
    allow_methods=['GET'],
    allow_headers=['*'],
)

@app.get('/api/health')
def health():
    return {'status': 'ok', 'snapshotReady': SNAPSHOT.is_file(),
            'modelResultsReady': MODELS.is_file()}

@app.get('/api/dashboard')
def dashboard():
    if not SNAPSHOT.is_file():
        raise HTTPException(status_code=404, detail=(
            'Dashboard data not exported yet. Run python main.py after adding '
            'export_dashboard_data(cleaned_df) near the end of main().'))
    with SNAPSHOT.open(encoding='utf-8') as f:
        return json.load(f)

@app.get('/api/models')
def models():
    if not MODELS.is_file():
        raise HTTPException(status_code=404, detail='Run the Spark project to generate outputs/results/model_comparison.csv')
    output = []
    with MODELS.open(newline='', encoding='utf-8-sig') as f:
        for row in csv.DictReader(f):
            normalized = {k.strip().lower(): v for k, v in row.items() if k}
            try:
                output.append({'model': normalized['model'],
                               'rmse': float(normalized['rmse']),
                               'mae': float(normalized['mae']),
                               'r2': float(normalized['r2'])})
            except (KeyError, ValueError) as exc:
                raise HTTPException(500, detail=f'Malformed model_comparison.csv: {exc}')
    return output

@app.get('/api/charts')
def charts():
    if not CHARTS.is_dir():
        return []
    return [{'name': f.stem.replace('_', ' ').title(), 'filename': f.name,
             'url': f'/api/chart/{f.name}'} for f in sorted(CHARTS.glob('*.png'))]

@app.get('/api/chart/{filename}')
def chart(filename: str):
    # No arbitrary path access or unsupported files.
    if not filename.endswith('.png') or filename != os.path.basename(filename):
        raise HTTPException(400, detail='Only PNG chart filenames are allowed')
    file = CHARTS / filename
    if not file.is_file():
        raise HTTPException(404, detail='Chart not found')
    return FileResponse(file, media_type='image/png')
